In [1]:
import os
import pandas as pd
import numpy as np
import anndata
import time
import matplotlib.pyplot as plt
import json
import requests

In [4]:
download_base = '../../../abc_download_root'

url = 'https://allen-brain-cell-atlas.s3-us-west-2.amazonaws.com/releases/20230630/manifest.json'
manifest = json.loads(requests.get(url).text)
    
metadata = manifest['file_listing']['Allen-CCF-2020']['metadata']

Read in parcellation annotation term set dataframe

In [5]:
rpath = metadata['parcellation_term_set']['files']['csv']['relative_path']
file = os.path.join( download_base, rpath)
term_sets = pd.read_csv(file)
term_sets.set_index('label', inplace=True)
term_sets

,description,name,parcellation_terminology_label,term_set_order,parent_term_set_label
label,,,,,
AllenCCF-Ontology-2017-ORGA,organ,organ,AllenCCF-Ontology-2017,0,NaN
AllenCCF-Ontology-2017-CATE,mouse brain anatomical catergories,category,AllenCCF-Ontology-2017,1,AllenCCF-Ontology-2017-ORGA
AllenCCF-Ontology-2017-DIVI,mouse brain divisions,division,AllenCCF-Ontology-2017,2,AllenCCF-Ontology-2017-CATE
AllenCCF-Ontology-2017-STRU,mouse brain structures,structure,AllenCCF-Ontology-2017,3,AllenCCF-Ontology-2017-DIVI
AllenCCF-Ontology-2017-SUBS,mouse brain substructures,substructure,AllenCCF-Ontology-2017,4,AllenCCF-Ontology-2017-STRU

Read in parcellation annotation term dataframe

In [4]:
rpath = taxonomy_metadata['cluster_annotation_term']['files']['csv']['relative_path']
file = os.path.join( download_base, rpath)
term = pd.read_csv(file)

other_term = pd.DataFrame(columns=term.columns)
other_term.loc[0,'name'] = 'Other'
other_term.loc[0,'cluster_annotation_term_set_name'] = 'neurotransmitter'
other_term.loc[0,'color_hex_triplet'] = '#ebebeb'
other_term.loc[0,'term_set_order'] = 0
other_term.loc[0,'term_order'] = 9
term = pd.concat([term,other_term],ignore_index=True)

term.sort_values(['term_set_order','term_order'],inplace=True)

Find and store first child for each term

In [5]:
term.head(5)

,label,name,cluster_annotation_term_set_label,parent_term_label,parent_term_set_label,term_set_order,term_order,cluster_annotation_term_set_name,color_hex_triplet
0,CCN20230504_NEUR_Glut,Glut,CCN20230504_NEUR,NaN,NaN,0,0,neurotransmitter,#2B93DF
1,CCN20230504_NEUR_GABA,GABA,CCN20230504_NEUR,NaN,NaN,0,1,neurotransmitter,#FF3358
2,CCN20230504_NEUR_Glut-GABA,Glut-GABA,CCN20230504_NEUR,NaN,NaN,0,2,neurotransmitter,#0a9964
3,CCN20230504_NEUR_Chol,Chol,CCN20230504_NEUR,NaN,NaN,0,3,neurotransmitter,#73E785
4,CCN20230504_NEUR_Dopa,Dopa,CCN20230504_NEUR,NaN,NaN,0,4,neurotransmitter,#fcf04b

In [6]:
filtered = term[pd.notna(term['parent_term_label'])]
first_child = filtered.groupby('parent_term_label')[['label','name','term_order','cluster_annotation_term_set_name']].first()
first_child

,label,name,term_order,cluster_annotation_term_set_name
parent_term_label,,,,
CCN20230504_CLAS_01,CCN20230504_SUBC_001,001 Car3 Glut,0,subclass
CCN20230504_CLAS_02,CCN20230504_SUBC_025,025 L6b EPd Glut,24,subclass
CCN20230504_CLAS_03,CCN20230504_SUBC_034,034 DG Glut,33,subclass
CCN20230504_CLAS_04,CCN20230504_SUBC_036,036 Vip Gaba,35,subclass
CCN20230504_CLAS_05,CCN20230504_SUBC_040,040 Lamp5 Lhx6 Gaba,39,subclass
...,...,...,...,...
CCN20230504_SUPT_1041,CCN20230504_CLUS_5194,5194 DC NN,5189,cluster
CCN20230504_SUPT_1042,CCN20230504_CLUS_5197,5197 B cells NN,5192,cluster
CCN20230504_SUPT_1043,CCN20230504_CLUS_5198,5198 ILC NN,5193,cluster
CCN20230504_SUPT_1044,CCN20230504_CLUS_5199,5199 NK cells NN,5194,cluster
CCN20230504_SUPT_1045,CCN20230504_CLUS_5200,5200 T cells NN,5195,cluster

In [7]:
term.set_index('label',inplace=True)
term.loc[first_child.index,'first_child_label'] = first_child['label']
term.loc[first_child.index,'first_child_term_set_name'] = first_child['cluster_annotation_term_set_name']
term.reset_index(inplace=True)

In [8]:
term[pd.notna(term['first_child_label'])].head(5)

,label,name,cluster_annotation_term_set_label,parent_term_label,parent_term_set_label,term_set_order,term_order,cluster_annotation_term_set_name,color_hex_triplet,first_child_label,first_child_term_set_name
17,CCN20230504_CLAS_01,01 IT-ET Glut,CCN20230504_CLAS,NaN,NaN,2,0,class,#f74294,CCN20230504_SUBC_001,subclass
18,CCN20230504_CLAS_02,02 NP-CT-L6b Glut,CCN20230504_CLAS,NaN,NaN,2,1,class,#61e2a4,CCN20230504_SUBC_025,subclass
19,CCN20230504_CLAS_03,03 MOB-DG-IMN,CCN20230504_CLAS,NaN,NaN,2,2,class,#16f2f2,CCN20230504_SUBC_034,subclass
20,CCN20230504_CLAS_04,04 CGE GABA,CCN20230504_CLAS,NaN,NaN,2,3,class,#cdef67,CCN20230504_SUBC_036,subclass
21,CCN20230504_CLAS_05,05 MGE GABA,CCN20230504_CLAS,NaN,NaN,2,4,class,#f954ee,CCN20230504_SUBC_040,subclass

Read in the cluster annotation term name pivot table and sort it

In [9]:
rpath = taxonomy_metadata['cluster_to_cluster_annotation_membership_pivoted']['files']['csv']['relative_path']
file = os.path.join( download_base, rpath)
df = pd.read_csv(file)
df = df.fillna('Other')
df_sorted = df.sort_values(['class','subclass','supertype','cluster'])
df_sorted

,cluster_alias,neurotransmitter,division,class,subclass,supertype,cluster
125,128,Glut,1 Pallium glutamatergic,01 IT-ET Glut,001 Car3 Glut,0001 Car3 Glut_1,0001 Car3 Glut_1
126,129,Glut,1 Pallium glutamatergic,01 IT-ET Glut,001 Car3 Glut,0001 Car3 Glut_1,0002 Car3 Glut_1
127,130,Glut,1 Pallium glutamatergic,01 IT-ET Glut,001 Car3 Glut,0001 Car3 Glut_1,0003 Car3 Glut_1
140,143,Glut,1 Pallium glutamatergic,01 IT-ET Glut,001 Car3 Glut,0001 Car3 Glut_1,0004 Car3 Glut_1
128,131,Glut,1 Pallium glutamatergic,01 IT-ET Glut,001 Car3 Glut,0002 Car3 Glut_2,0005 Car3 Glut_2
...,...,...,...,...,...,...,...
5168,5279,Other,7 Immune,32 Immune,305 DC NN,1041 DC NN,5196 DC NN
5164,5275,Other,7 Immune,32 Immune,306 Lymphoid NN,1042 B cells NN,5197 B cells NN
5161,5272,Other,7 Immune,32 Immune,306 Lymphoid NN,1043 ILC NN,5198 ILC NN
5163,5274,Other,7 Immune,32 Immune,306 Lymphoid NN,1044 NK cells NN,5199 NK cells NN
5162,5273,Other,7 Immune,32 Immune,306 Lymphoid NN,1045 T cells NN,5200 T cells NN

Create a lookup by name dataframes for each term set

In [10]:
lookup = {}
for tag in term_sets['name'] :
    #print(tag)
    pred = (term['cluster_annotation_term_set_name'] == tag)
    filtered = term[pred].copy()
    filtered.set_index('name', inplace=True)
    lookup[tag] = filtered

Helper functions to lookup an term attribut and format a cell in the html table

In [11]:
def get_value( c, n, v ) :
    return lookup[c].loc[n][v]

def format_cell (df,c,add_id=False,add_plus=False,add_minus=False) :

    divs = pd.DataFrame(index=df.index)
    
    pattern = '<div class="circle" style="background-color:%s"></div>'
    divs['circle'] = [ pattern % get_value(c,x,'color_hex_triplet') for x in df[c] ]
    
    pattern = '<div class="celltext">%s</div>'
    divs['name'] = [ pattern % x for x in df[c] ]
   
    divs['id'] = ''
    if add_id :
        pattern = '<div id="%s"></div>'
        divs['id'] = [ pattern % get_value(c,x,'label') for x in df[c] ]
        
    divs['plus'] = ''
    if add_plus :
        pattern = '<div class="celltext"><a href="%s.html#%s">[+]</a></div>'
        divs['plus'] = [ pattern % (get_value(c,x,'first_child_term_set_name'),
                                    get_value(c,x,'first_child_label')) for x in df[c] ]
        
    divs['minus'] = ''
    if add_minus :
        pattern = '<div class="celltext"><a href="%s.html#%s">[-]</a></div>'
        divs['minus'] = [ pattern % (get_value(c,x,'cluster_annotation_term_set_name'),
                                    get_value(c,x,'label')) for x in df[c] ]
    
    cols = ['id','circle','name','plus','minus']
    output = divs[cols].apply(lambda row: ''.join(row.values.astype(str)), axis=1)
    return output

Helper function to create html document

In [12]:
def create_html (df,ts,file,title) :
    
    # apply formatter to each term set
    df_formatted = df.copy()
    
    for tag in term_sets['name'] :
        if tag in df_formatted.columns :
            
            add_id = False
            if tag == ts :
                add_id = True
                
            add_plus = False
            if tag == ts and tag not in ('cluster','neurotransmitter', 'division') :
                add_plus = True
                
            add_minus = False
            if tag != ts and tag not in ('neurotransmitter') :
                add_minus = True
                
            df_formatted[tag] = format_cell(df,tag,add_id,add_plus,add_minus)
            
            
    output = df_formatted.to_html(index=False, na_rep='',
                        render_links=True,escape=False,
                        classes="mystyle")

    html_string = '''
    <html>
    <head><title>%s</title></head>
    <link rel="stylesheet" type="text/css" href="../simple_style.css"/>
    <body>
    {table}
    </body>
    </html>.
    ''' % title

    # OUTPUT AN HTML FILE
    with open(file, 'w') as f:
        f.write(html_string.format(table=output))

In [13]:
output_directory = 'WMB-taxonomy'
os.makedirs( output_directory, exist_ok=True)

In [14]:
df_supertype = df_sorted[['class']].copy()
df_supertype.drop_duplicates(inplace=True)

file = os.path.join(output_directory,'class.html')
title = 'WMB-taxonmy: cell type classes'
create_html(df_supertype, 'class',file, title)
print(len(df_supertype))

32

In [15]:
df_supertype = df_sorted[['class','subclass']].copy()
df_supertype.drop_duplicates(inplace=True)

file = os.path.join(output_directory,'subclass.html')
title = 'WMB-taxonmy: cell type subclasses'
create_html(df_supertype, 'subclass',file, title)
print(len(df_supertype))

307

In [16]:
df_supertype = df_sorted[['class','subclass','supertype']].copy()
df_supertype.drop_duplicates(inplace=True)

file = os.path.join(output_directory,'supertype.html')
title = 'WMB-taxonmy: cell type supertypes'
create_html(df_supertype, 'supertype',file, title)
print(len(df_supertype))

1115

In [17]:
df_supertype = df_sorted[['class','subclass','supertype','cluster','neurotransmitter']].copy()
df_supertype.drop_duplicates(inplace=True)

file = os.path.join(output_directory,'cluster.html')
title = 'WMB-taxonmy: cell type clusters'
create_html(df_supertype,'cluster',file, title)
print(len(df_sorted))

5196

In [18]:
df_supertype = df_sorted[['division']].copy()
df_supertype.drop_duplicates(inplace=True)

file = os.path.join(output_directory,'division.html')
title = 'WMB-taxonmy: cell type divisions'
create_html(df_supertype, 'division', file, title)
print(len(df_supertype))

7

In [19]:
df_supertype = df_sorted[['neurotransmitter']].copy()
df_supertype.drop_duplicates(inplace=True)

file = os.path.join(output_directory,'neurotransmitter.html')
title = 'WMB-taxonmy: neurotransmitter types'
create_html(df_supertype, 'neurotransmitter', file, title)
print(len(df_supertype))

10